name: feature-3 mocha test

on:
  pull_request:
    branches: [Develop]
  push:
    branches: [feature/3]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        npm install @slack/rtm-api dotenv
        npm install mocha -g
        npm install axios
        npm install cheerio
        mocha test/feature-3.spec.js
      env:
        CI: true